name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  build:
    if: github.event_name == 'schedule' || (github.event.repository.owner.id == github.event.sender.id) || github.event.inputs.manual
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build unbound
      run: |
        echo "/usr/local/unbound" | bash unbound_static_build.sh
        pushd /usr/local
          sudo tar -zcf unbound-master-linux-x64.tar.gz unbound
        popd

    - name: Get latest version
      run: |
        VERSION=$(curl -s https://api.github.com/repos/NLnetLabs/unbound/commits/master | grep -oP '"sha": "\K(.*)(?=")' | head -1)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      shell: bash

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: unbound-master-static
        allowUpdates: true
        tag: static
        commit: master
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: /usr/local/unbound-master-linux-x64.tar.gz
        draft: false
        body: |
          Latest commit from the master branch:
          https://github.com/NLnetLabs/unbound/commit/${{ env.VERSION }}

    - name: Commit and push branch
      run: |
          mv /usr/local/unbound-master-linux-x64.tar.gz /home/unbound-master-linux-x64.tar.gz
          cd /home || exit 1
          git init
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b release
          git add unbound-master-linux-x64.tar.gz
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

    - name: Purge jsDelivr CDN
      run: |
        curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/unbound-master-linux-x64.tar.gz"

    - name: Set release output
      run: echo "release_id=${{ steps.create_release.outputs.release_id }}" >> $GITHUB_ENV
